### ISSUE TITLE
jcpi Maven repository is not accessible

### ISSUE THREAD

**Issue by lrozenblyum** [fluxroot/jcpi#116]
Hello!
While building chess software (Travis build https://travis-ci.com/lrozenblyum/chess/builds/106622269) I encountered an issue

http://maven.fluxchess.com/release/com/fluxchess/jcpi/1.4.0/jcpi-1.4.0.pom
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>96FB39FB2F3445F2</RequestId>
<HostId>
/HlIg16uGeywVGfTeMQYnhufkSwTWhbO6DhMS+OXz72VSLOIvU3+bkHeTSjURPnOXwXv5iuQIOE=
</HostId>
</Error>
```

Could you please fix the maven repository settings?

**Comment by fluxroot** [comment]
Hey there!
Thanks for asking. I recently moved JCPI from the Amazon S3 repository to Maven Central. Just remove the `maven.fluxchess.com` repository and use the following coordinates for the new JCPI dependency:
```
<dependency>
    <groupId>com.fluxchess.jcpi</groupId>
    <artifactId>jcpi</artifactId>
    <version>1.4.1</version>
</dependency>
```

**Comment by fluxroot** [comment]
Here's the artifact info page from search: https://search.maven.org/artifact/com.fluxchess.jcpi/jcpi/1.4.1/jar

**Comment by lrozenblyum** [comment]
Thank you! Working on migration to the new jcpi location and version!
BTW: previously a test-jar was also available in the old repository but it doesn't exist in Maven central (just wondering if it's ok, since my project doesn't depend on it as a matter of fact)

**Comment by fluxroot** [comment]
It should be quite easy to migrate the build.
Yes, I dropped the test-jar as it adds no benefit to the release. I'll close this issue. Feel free to reopen if something's not working.

**Comment by lrozenblyum** [comment]
Thanks @fluxroot for your support. The migration to new JCPI succeeded.
